### ISSUE TITLE
How is this different from PHPCS

### ISSUE THREAD

**Issue by azngeek** [andkirby/commithook#7]
Hello, 

i had a fast look into the code but how is this different from running PHPCS directly?

greets

**Comment by andkirby** [comment]
Hello,

I'm pretty sure PHPCS is good for this. And you know I use it in PhpStorm to validate my code in development.
I didn't just get a fast way to use PHPCS within Magento. I had some draft script which worked good but it was hard to support. Thus was created CommitHook project.
We use it and it works so far. I'm pretty sure that there is exist a way to use PHPCS via pre-commit.
