### ISSUE TITLE
Describing type of params

### ISSUE THREAD

**Issue by virtual97** [andkirby/commithook#8]
Hi! Found that when to describe PHPDoc params like this:
*@param null|array $stores*,
commit hooks will show next error:
*There are found "@var null" or "@param null" in PHPDoc block at least 1 times. Please describe it with more types.*.
But, if to write in this way, validation error is absent:
*@param array|null $stores*
Looks like this is a bug.

**Comment by andkirby** [comment]
Yeah, it is. Thanks for the report.

**Comment by andkirby** [comment]
You know man, it doesn't make sense. I've I added tests and it works fine.
Could add more extended case?
