### ISSUE TITLE
Using braces in the PHTML code

### ISSUE THREAD

**Issue by virtual97** [andkirby/commithook#9]
Next code in phtml file
**<?php if ($this->getCollection()->getSize() &&
    ($this->getCollection()->getLastPageNumber() > $this->getCollection()->getCurPage())): ?>**

Will cause to wrong message:
**No ability to use braces in the PHTML code. Please use alternative syntax as if..endif. Original line: <?php if ($this->getCollection()->getSize() &&**

Looks like this is a bug.

**Comment by andkirby** [comment]
Thanks for this issue. Unfortunately, there is no way to validate it. But I added validation for oneline conditions. Multiline code will be skipped.

**Comment by andkirby** [comment]
It was included in release v1.6.10-alpha.9.
